name: Test and Deploy

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest

  deploy:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_SSH_KEY }}
          username: ec2-user
          script: |

            cd /home/ec2-user/cicd-testing
            git pull origin main

            docker stop my-gradio-app || true
            docker rm my-gradio-app || true

            docker build -t my-gradio-app .

            docker run -d --name my-gradio-app -p 7860:7860 my-gradio-app